# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development: 
  adapter: postgresql 
  encoding: utf8 
  database: lev_ehad_development 
  username: yosy
  host: localhost
  pool: 5
  port: 5432
  