production: &default
  adapter: postgresql
  database: lev_ehad_production
  pool: 5
  timeout: 5000

development: &default
  adapter: postgresql
  database: lev_ehad_development
  pool: 5
  timeout: 5000
  host: localhost

test: &test
  <<: *default
  database: lev_ehad_test
  min_messages: warning